### PR TITLE
chore: update axios peer dependency to >=0.26.0

### PR DESCRIPTION
**Pull request by palmithor**
Think it is time to bump Axios and also allow more versions.

### CODE REVIEW

**Comment by sybers** [comment]
Hi @palmithor !

That's a good idea, however as axios is still `0.x` I'd prefer to keep the semver range to `^0.26.0` to avoid breaking changes from their side.
Can you do that change please ?

**Comment by palmithor** [comment]
Hey @sybers .. `^0.26.0` or `^0.27.0`?

**Comment by sybers** [comment]
Huh I guess it will be easier to maintain with your semver range, otherwise I'll have to update the version too frequently. I'll merge your PR as is. Thanks :)

**Comment by palmithor** [comment]
Hey @sybers , any plans to release a new version with this update? We have peer dependency issue and it'd be very nice to get this in.

**Pull request merged**
