### PR TITLE
Enabling Manifest V3 support - Tested in v2 and v3

### PR DESCRIPTION
**Pull request by arnthors**
@sybers  This library helped me out but I had to do some tweaks to get it working. Hopefully this PR helps.

My extension is on manifest v3 so I had to get it working for v3 which involved:
* Manifest v3 service worker does not support `xmlhttprequest` like v2 background does; adding a fetch adapter (and regenerator-runtime) addresses this. 
* I was seeing some errors due to `request.config.transformRequest` and `request.config.transformRequest` being set to `[null]` but adding a catch and empty array assignment for these cases resolves that.

Verified functionality on manifest v2 and manifest v3.

### CODE REVIEW

**Comment by sybers** [comment]
Hi @arnthors and thank you for submitting this PR !

I will have a look at the code changes and probably will make some comments if there are things we can improve :)

I'd also like to try this out myself with a sample chrome extension using manifest V3 to confirm everything is working as intended. If you already have a repo with a test extension that would be nice.

**Comment by arnthors** [comment]
@sybers I don't have a repo but I set mine up using https://github.com/njzydark/chrome-extension-boilerplate - Attached is a zipfile with my test project - just install dependancies and to build it run `npm run build`


[test-chrome-manifest-v2-v3.zip](https://github.com/sybers/axios-chrome-messaging-adapter/files/8352864/test-chrome-manifest-v2-v3.zip)

**Comment by arnthors** [comment]
@sybers is there anything else I could do to help out here?

**Comment by sybers** [comment]
@arnthors I'll take care of the comments I left and will merge your PR asap, thanks for working on this :)

**Pull request merged**
